version: "3.2"

services:
  db:
    image: postgres:latest
    restart: always
    container_name: fileasy-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app:
    restart: unless-stopped
    ports:
      - 5000:5000
    container_name: fileasy-app
    build: .
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro

  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path=/var/www/certbot --agree-tos --no-eff-email -d fileasy.ru
