version: "3.2"

services:
  db:
    image: postgres:latest
    restart: always
    container_name: fileasy-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
